logo: false
timeformat: "MMM, D YYYY"
podcast: true
lazyload: true
highlight:
  enable: true
  lightmode: 'atom-one-light'
  darkmode: 'atom-one-dark'
navbar:
  - ['https://init.blog', 'fa fa-cube']
  - ['https://github.com/guiqiqi', 'fa fa-github']
  - ['/feed', 'fa fa-rss']
menubar:
  - ['/about', 'About']
  - ['/archives', 'Archives']